# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(default='sem cargo', max_length=50),
            preserve_default=False,
        ),
    ]
