# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='fddfsd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.FileField(default='dsdfsd', upload_to=b''),
            preserve_default=False,
        ),
    ]
