# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
