# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionario', '0002_funcionario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
    ]
