# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionario', '0003_remove_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(default='tecnico', max_length=100),
            preserve_default=False,
        ),
    ]
